version: "3.1"
services:
  mysql:
    env_file: ./.env
    image: mysql:5.7.16
    container_name: mysql
    volumes:
      - ./datanew/db:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"
  app:
    image: node:latest
    container_name: nodejs-iot
    depends_on:
        - mysql
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mysql:mysql
    ports:
      - "3080:3080"
    entrypoint: /application/start_application.sh
    env_file: ./.env
    environment:
      "NODE_ENV": "development"
