version: "3.1"
services:
  mysql:
    env_file: ./.env
    image: mysql:5.7.16
    container_name: mysql
    volumes:
      - ./datanew/db:/var/lib/mysql
    restart: always
    ports:
      - "8306:8306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  app:
    image: node:latest
    container_name: nodejs-iot
    depends_on:
        - mysql
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mysql
    ports:
      - "3080"
    entrypoint: /application/start_application.sh
    env_file: ./.env
    environment:
      "NODE_ENV": "development"

